package terminal

import (
	"fmt"
	"strings"
)

// generateGhostty creates a shell script that uses Ghostty's keybindings
// to create a split-pane layout with SSH connections to agents.
//
// Ghostty doesn't have a session config format like iTerm2 or Kitty,
// so we generate a shell script that:
// 1. Opens Ghostty with the first agent
// 2. Uses ghostty CLI or keybind simulation to create splits
// 3. Runs SSH commands in each pane
func generateGhostty(cfg Config) string {
	var b strings.Builder

	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Ghostty multi-agent launcher\n")
	b.WriteString("# Generated by cloudcoop terminal generate\n")
	b.WriteString("#\n")
	b.WriteString(fmt.Sprintf("# Grid: %dx%d (%d panes)\n", cfg.Grid.Cols, cfg.Grid.Rows, cfg.Grid.Cols*cfg.Grid.Rows))
	b.WriteString(fmt.Sprintf("# Agents: %d\n", len(cfg.Sessions)))
	b.WriteString("#\n")
	b.WriteString("# Usage: chmod +x this-script.sh && ./this-script.sh\n")
	b.WriteString("\n")
	b.WriteString("set -e\n")
	b.WriteString("\n")

	// Check for Ghostty
	b.WriteString("# Check if Ghostty is installed\n")
	b.WriteString("if ! command -v ghostty &> /dev/null; then\n")
	b.WriteString("    echo \"Error: Ghostty is not installed or not in PATH\"\n")
	b.WriteString("    echo \"Install Ghostty from: https://ghostty.org\"\n")
	b.WriteString("    exit 1\n")
	b.WriteString("fi\n")
	b.WriteString("\n")

	// Generate SSH commands array
	b.WriteString("# SSH commands for each agent\n")
	b.WriteString("declare -a COMMANDS=(\n")
	for i, session := range cfg.Sessions {
		if i >= cfg.Grid.Cols*cfg.Grid.Rows {
			break // Don't exceed grid capacity
		}
		cmd := sshCommandForBash(cfg, session.Index)
		b.WriteString(fmt.Sprintf("    %q  # %s\n", cmd, session.Name))
	}
	b.WriteString(")\n")
	b.WriteString("\n")

	// Ghostty approach: Use multiple windows since split automation is limited
	// For a proper multi-pane setup, we recommend using iTerm2 or Kitty
	b.WriteString("# Launch Ghostty windows for each agent\n")
	b.WriteString("# Note: Ghostty doesn't support programmatic splits like iTerm2/Kitty.\n")
	b.WriteString("# This launches separate windows. For a single window with splits,\n")
	b.WriteString("# use --format=iterm2 or --format=kitty instead.\n")
	b.WriteString("\n")

	b.WriteString("echo \"Launching ${#COMMANDS[@]} Ghostty windows...\"\n")
	b.WriteString("\n")

	b.WriteString("for cmd in \"${COMMANDS[@]}\"; do\n")
	b.WriteString("    ghostty -e bash -c \"$cmd; exec bash\" &\n")
	b.WriteString("    sleep 0.3  # Brief delay to prevent overwhelming the system\n")
	b.WriteString("done\n")
	b.WriteString("\n")

	b.WriteString("echo \"Done! ${#COMMANDS[@]} agent windows launched.\"\n")
	b.WriteString("echo \"Use your window manager to arrange them in a grid.\"\n")

	return b.String()
}

// sshCommandForBash builds the SSH command for use inside a bash script.
// Unlike sshCommand, this doesn't escape the && for the outer shell.
func sshCommandForBash(cfg Config, windowIndex int) string {
	portArg := ""
	if cfg.Port != 22 {
		portArg = fmt.Sprintf("-p %d ", cfg.Port)
	}
	tmuxCmd := fmt.Sprintf("tmux select-window -t %s:%d && tmux attach -t %s", cfg.Session, windowIndex, cfg.Session)
	return fmt.Sprintf("ssh %s-t %s@%s '%s'", portArg, cfg.User, cfg.Host, tmuxCmd)
}
