package terminal

import (
	"fmt"
	"strings"
)

// generateITerm2 creates an AppleScript that opens iTerm2 with a grid
// of split panes, each connected to a different agent session.
func generateITerm2(cfg Config) string {
	var b strings.Builder

	b.WriteString("-- iTerm2 multi-agent launcher\n")
	b.WriteString("-- Generated by cloudcoop terminal generate\n")
	b.WriteString("--\n")
	b.WriteString(fmt.Sprintf("-- Grid: %dx%d (%d panes)\n", cfg.Grid.Cols, cfg.Grid.Rows, cfg.Grid.Cols*cfg.Grid.Rows))
	b.WriteString(fmt.Sprintf("-- Agents: %d\n", len(cfg.Sessions)))
	b.WriteString("--\n")
	b.WriteString("-- Usage: osascript this-script.scpt\n")
	b.WriteString("\n")

	b.WriteString("tell application \"iTerm2\"\n")
	b.WriteString("    activate\n")
	b.WriteString("    \n")
	b.WriteString("    -- Create a new window\n")
	b.WriteString("    set newWindow to (create window with default profile)\n")
	b.WriteString("    \n")
	b.WriteString("    tell newWindow\n")
	b.WriteString("        -- Get the initial session\n")
	b.WriteString("        set initialSession to current session of current tab\n")
	b.WriteString("        \n")

	// We'll build the grid row by row
	// Each row needs (cols-1) vertical splits
	// After the first row, we split horizontally to create new rows

	totalPanes := cfg.Grid.Cols * cfg.Grid.Rows
	sessionIdx := 0

	// Build array of commands
	var commands []string
	for i := 0; i < totalPanes && i < len(cfg.Sessions); i++ {
		cmd := sshCommandForAppleScript(cfg, cfg.Sessions[i].Index)
		commands = append(commands, cmd)
	}

	// Fill remaining slots with a placeholder if grid is larger than sessions
	for len(commands) < totalPanes {
		commands = append(commands, "echo 'No agent assigned to this pane'; exec bash")
	}

	// Create the grid using splits
	// Strategy: Create first row, then split each pane horizontally for subsequent rows

	b.WriteString("        -- Build the grid\n")
	b.WriteString("        set allPanes to {initialSession}\n")
	b.WriteString("        \n")

	// First, create all columns in the first row by splitting vertically
	if cfg.Grid.Cols > 1 {
		b.WriteString("        -- Create columns in first row (vertical splits)\n")
		b.WriteString("        set currentPane to initialSession\n")
		for col := 1; col < cfg.Grid.Cols; col++ {
			b.WriteString("        set newPane to (split vertically with default profile)\n")
			b.WriteString("        set end of allPanes to newPane\n")
			b.WriteString("        set currentPane to newPane\n")
		}
		b.WriteString("        \n")
	}

	// Now create additional rows by splitting each column pane horizontally
	if cfg.Grid.Rows > 1 {
		b.WriteString("        -- Create rows (horizontal splits from each column)\n")
		for row := 1; row < cfg.Grid.Rows; row++ {
			b.WriteString(fmt.Sprintf("        -- Row %d\n", row+1))
			for col := 0; col < cfg.Grid.Cols; col++ {
				paneIdx := col // The pane to split is at index col (from first row)
				b.WriteString(fmt.Sprintf("        tell item %d of allPanes\n", paneIdx+1))
				b.WriteString("            set newPane to (split horizontally with default profile)\n")
				b.WriteString("        end tell\n")
				b.WriteString("        set end of allPanes to newPane\n")
			}
		}
		b.WriteString("        \n")
	}

	// The allPanes array now has panes in order: first row left-to-right, then second row, etc.
	// But the order might be tricky due to how splits work. Let's assign commands.
	// Actually, let's simplify - just assign commands to panes by iterating through sessions

	b.WriteString("        -- Run SSH commands in each pane\n")

	// We need to carefully map grid positions to the pane order
	// With iTerm2, when you split, the new pane is the one you get
	// The order in allPanes is: initial, then col splits, then row splits

	// Simpler approach: just write commands to panes in order
	// The pane layout order after our splits will be:
	// First row: pane 1, pane 2, ... pane cols (left to right)
	// Second row: pane cols+1, ... etc
	// But since splits create new panes and original stays, we need to track carefully

	// Let's use a different approach - just iterate and assign
	for i, cmd := range commands {
		if sessionIdx >= len(cfg.Sessions) && i >= len(cfg.Sessions) {
			// This pane has no agent
			b.WriteString(fmt.Sprintf("        tell item %d of allPanes\n", i+1))
			b.WriteString(fmt.Sprintf("            write text %q\n", cmd))
			b.WriteString("        end tell\n")
		} else if i < len(cfg.Sessions) {
			b.WriteString(fmt.Sprintf("        -- %s (index %d)\n", cfg.Sessions[i].Name, cfg.Sessions[i].Index))
			b.WriteString(fmt.Sprintf("        tell item %d of allPanes\n", i+1))
			b.WriteString(fmt.Sprintf("            write text %q\n", cmd))
			b.WriteString("        end tell\n")
			sessionIdx++
		}
	}

	b.WriteString("    end tell\n")
	b.WriteString("end tell\n")

	return b.String()
}

// sshCommandForAppleScript builds the SSH command for use in AppleScript.
func sshCommandForAppleScript(cfg Config, windowIndex int) string {
	portArg := ""
	if cfg.Port != 22 {
		portArg = fmt.Sprintf("-p %d ", cfg.Port)
	}
	tmuxCmd := fmt.Sprintf("tmux select-window -t agents:%d && tmux attach -t agents", windowIndex)
	return fmt.Sprintf("ssh %s-t %s@%s '%s'", portArg, cfg.User, cfg.Host, tmuxCmd)
}
