package terminal

import (
	"fmt"
	"strings"
)

// generateKitty creates a Kitty session config file that opens a grid
// of split panes, each connected to a different agent session.
//
// Kitty session format documentation:
// https://sw.kovidgoyal.net/kitty/overview/#sessions
func generateKitty(cfg Config) string {
	var b strings.Builder

	b.WriteString("# Kitty multi-agent session\n")
	b.WriteString("# Generated by cloudcoop terminal generate\n")
	b.WriteString("#\n")
	b.WriteString(fmt.Sprintf("# Grid: %dx%d (%d panes)\n", cfg.Grid.Cols, cfg.Grid.Rows, cfg.Grid.Cols*cfg.Grid.Rows))
	b.WriteString(fmt.Sprintf("# Agents: %d\n", len(cfg.Sessions)))
	b.WriteString("#\n")
	b.WriteString("# Usage: kitty --session this-file.conf\n")
	b.WriteString("\n")

	// Kitty session format uses:
	// - `new_tab [title]` to create a new tab
	// - `layout <layout_name>` to set the layout
	// - `launch [options] <command>` to launch a command in a new window
	// - `split` to create splits

	// We'll use the grid layout for a perfect grid
	b.WriteString("# Use grid layout for evenly sized panes\n")
	b.WriteString("layout grid\n")
	b.WriteString("\n")

	// Set the tab title
	b.WriteString("# Create tab with agents\n")
	b.WriteString("new_tab agents\n")
	b.WriteString("\n")

	// Launch commands for each agent
	// The first launch uses the initial window, subsequent ones create splits
	totalPanes := cfg.Grid.Cols * cfg.Grid.Rows
	paneCount := 0

	for i, session := range cfg.Sessions {
		if paneCount >= totalPanes {
			break
		}

		cmd := sshCommandForKitty(cfg, session.Index)

		if i == 0 {
			// First pane - just launch
			b.WriteString(fmt.Sprintf("# %s (index %d)\n", session.Name, session.Index))
			b.WriteString(fmt.Sprintf("launch --title %q %s\n", session.Name, cmd))
		} else {
			// Subsequent panes - launch creates new windows in grid layout
			b.WriteString(fmt.Sprintf("# %s (index %d)\n", session.Name, session.Index))
			b.WriteString(fmt.Sprintf("launch --title %q %s\n", session.Name, cmd))
		}
		paneCount++
	}

	// If we have fewer sessions than grid slots, add empty shells
	for paneCount < totalPanes {
		b.WriteString("# Empty pane\n")
		b.WriteString(fmt.Sprintf("launch --title \"empty-%d\" bash\n", paneCount))
		paneCount++
	}

	b.WriteString("\n")
	b.WriteString("# Focus the first window\n")
	b.WriteString("focus\n")

	return b.String()
}

// sshCommandForKitty builds the SSH command for use in Kitty session config.
// Kitty's launch command takes the command and arguments directly (not as a shell string).
func sshCommandForKitty(cfg Config, windowIndex int) string {
	var parts []string
	parts = append(parts, "ssh")

	if cfg.Port != 22 {
		parts = append(parts, "-p", fmt.Sprintf("%d", cfg.Port))
	}

	parts = append(parts, "-t")
	parts = append(parts, fmt.Sprintf("%s@%s", cfg.User, cfg.Host))

	// The remote command needs to be a single argument
	tmuxCmd := fmt.Sprintf("tmux select-window -t agents:%d && tmux attach -t agents", windowIndex)
	parts = append(parts, tmuxCmd)

	return strings.Join(parts, " ")
}
